a = int(input("a = "))
b = int(input("b = "))
print("a + b = ", a + b,)
print("a - b = ", a - b,)
print("a / b = ", a // b,)
print("Restul impartirii lui a la b = ", a % b,)
print("a * b = ", a * b,)
print("a ** b = ", a ** b,)